### ISSUE TITLE
ImportError: No module named vat.vat_validation

### ISSUE THREAD

**Issue by stevenyaga** [saguas/frappe_base_vat#1]
Hi, 

I installed base_vat into erpnext site and it was successful. However, when i try save a new customer i get the error "ImportError: No module named vat.vat_validation". Could i have missed something ?

Regards

**Comment by saguas** [comment]
Hi.

Problems should now be solved. 
Please do, bench update or inside apps/base_vat do git pull then bench migrate. 

To be sure, check in desk inside setup->customize->Custom Field and check if is there Customer-vat_or_nif http://192.168.1.100:8010/desk#Form/Custom%20Field/Customer-vat_or_nif,  Customer-validate_vat http://192.168.1.100:8010/desk#Form/Custom%20Field/Customer-validate_vat andCompany-vies_vat_check http://192.168.1.100:8010/desk#Form/Custom%20Field/Company-vies_vat_check. Inside Custom Script must be  Customer-Client http://192.168.1.100:8010/desk#Form/Custom%20Script/Customer-Client.

If the problem persist please tell me.

Thanks,
Luís Fernandes.

**Comment by stevenyaga** [comment]
Hi,

It does not fix it. Instead there is a new error " TypeError: 'NoneType' object has no attribute '**getitem**'

Regards

**Comment by saguas** [comment]
Sorry, i thinks it is now fixed.

Let me know.

Thanks,
Luís Fernandes.

**Comment by stevenyaga** [comment]
It is now fixed. Thanks so much
